### ISSUE TITLE
How to close the keyboard programmatically?

### ISSUE THREAD

**Issue by nicetomytyuk** [furcan/KioskBoard#12]
Is there a way to close the keyboard programmatically on a button click or other?

**Comment by furcan** [comment]
Hi @nicetomytyuk 

The keyboard elements have been designed to close automatically when the user clicks to any area except for the related input element or the keyboard itself.

So, if you want to close an opened keyboard element without this flow, you can use a simple click method anywhere you wanted:

```js
window.document.body.click();
```
