### ISSUE TITLE
How to reset the input?

### ISSUE THREAD

**Issue by nicetomytyuk** [furcan/KioskBoard#13]
I have an issue while using the KioskBoard, i use it with a bootstrap modal which has an input, once the modal is closed i'm trying to reset the input value by setting it to "" or to 0, but once i open it again and press one of the keys of the KioskBoard it will even set the old value, does the KioskBoard save the old value in some data attribute?

**Comment by furcan** [comment]
Hi @nicetomytyuk 

You have to be sure to close/remove the keyboard element too with your modal element. 

Thanks.

**Comment by nicetomytyuk** [comment]
Actually i was calling `KioskBoard.Run()` on page init, by moving it inside the even of "modal open" i solved the issue
