### ISSUE TITLE
No incoming input to vuetify v-text-fields

### ISSUE THREAD

**Issue by farhadnowzari** [furcan/KioskBoard#15]
I think there is  a conflict between how Vuetify controls the keyboard input and Kioskboard.
If you add Vuetify textboxes to your project and give the id of the field to Kioskboard to load on focus the gonna be no input.

To reproduce it just add a vue project and vuetify to it.
Then get the id of the field(class is not possible at first glance that I had because vuetify wraps the textbox inside a div element) and then give it to the kiosk and then when the keyboard popsup you have no input.

Here is an example (Its dirty but you get the point ^^)
https://jsfiddle.net/gLw5e1rj/9/

**Comment by furcan** [comment]
Hi @farhadnowzari ,

I am not sure the KioskBoard works with VUE as fully compatible, so I can not reproduce or solve this issue as well. If you have any kind of solution etc. any help is welcome.

Thank you.
Furkan.
