### ISSUE TITLE
Virtual keyboard does not take input maxlen attribute into account

### ISSUE THREAD

**Issue by omogenot** [furcan/KioskBoard#17]
Hi,

I noticed that the original code does not check the field length against the maxlength attribute that might be associated to the input field.
In order to do that, the javascript `inputFocusListener` function must be modified to include a new variable:
```
          var theInputMaxLenAttr = theInput.getAttribute('maxlength');
```
and to use this value later on in the `keysClickListeners` function:
```
                  // add value by index
                  if ((theInputMaxLenAttr === null) || (theInputValArray.length < theInputMaxLenAttr)) {
                      theInputValArray.splice(theInputSelIndex, 0, keyValue);
                  }
```

**Comment by furcan** [comment]
Hi @omogenot 

Max and MaxLength attribute controls have been added.

Thanks, 
Furkan.
