### ISSUE TITLE
How to add the "Enter" key

### ISSUE THREAD

**Issue by rnleal** [furcan/KioskBoard#23]
Is there a way to add the "enter/return" key?

**Comment by furcan** [comment]
Hi @rnleal ,

There is not a feature that can be added an Enter/Return key right now. I will think about this for the next versions.

I suggest adding an Enter button next to the input element to solve this request without Kioskboard.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
| `<input/>` | `<enterButton/>` |
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


Thanks,
Furkan.
