### ISSUE TITLE
Dynamic language change

### ISSUE THREAD

**Issue by MSD2000** [furcan/KioskBoard#28]
Is there some way of implementing dynamic language change when the keyboard is running? I imagine it like having aditional buttons with language abbriviation (RU/EN/BG), and when the user clicks them, the keyboard changes its layout and buttons.

**Comment by furcan** [comment]
Hi @MSD2000 ,

There is no such feature related to this request. You can fork this library to create your own solution as well.

Thanks,
Furkan.
