### ISSUE TITLE
Keys Reordering for numpad

### ISSUE THREAD

**Issue by onuh** [furcan/KioskBoard#30]
Is there a way to reorder the numpad to start from 1 at the top and end with 0, then the backspace? Can we have the enter key on the numpad? How about a clipboard option to paste data directly from clipboard to input?

**Comment by furcan** [comment]
Hi @onuh ,

Unfortunately, there is no such option to reorder the Numpad. I will consider this request for the next updates.
Till then, you can reorder the static key via the source file if you want.

Thanks,
Furkan.

**Comment by onuh** [comment]
Thanks for your reply.

I await your updates. Such an awesome plugin you have there.

I also want to add, keyup events aren't firing with the keyboard. Can you
please work on it?

**Comment by furcan** [comment]
Hi @onuh ,

A `change `event will be fired for each keypress. You can add a `change `event listener to the input elements instead of `keyup`.

And for the main issue; I will add a new option that allows the user to set custom numbers from `1` to `9` in any order for the Numpad type of keyboard. `0` will stay as it is.

Thanks,
Furkan.

**Comment by onuh** [comment]
Thanks for the suggestions and updates.

**Comment by furcan** [comment]
Hi @onuh ,

KioskBoard v2.0.0 has been released. 

A new option has been added and the option name is `keysNumpadArrayOfNumbers`.
An Array of Numbers from 0 to 9 in any order can be set to this option to use a custom Numpad.

Also, this is a major release. Please take a look at the [CHANGELOG](https://github.com/furcan/KioskBoard/blob/main/CHANGELOG.md) before updating your current projects.

Thanks,
Furkan.

**Comment by onuh** [comment]
Thanks a bunch.

I used your plugin for my app here:
https://smartchurchattendance.com.ng/smartChurch/downloads/Smart_Church_Mobile_1_2.0.apk
