### ISSUE TITLE
Custom key with multiple characters

### ISSUE THREAD

**Issue by skullab** [furcan/KioskBoard#31]
if I create a key that inserts more characters, it is no longer possible to delete the input because the length of the input
exceeds the length of the aray where the characters are saved. I have created a fork to solve this problem.
https://github.com/skullab/KioskBoard

**Comment by furcan** [comment]
Hi @skullab ,

Thanks for the report.

Could you please share your init function(especially the keys) for reproducing the issue on my local? And also, I will review the PR as well.

Thanks,
Furkan.

**Comment by skullab** [comment]
```js
keysArrayOfObjects = [
     // other object rows configurations...
     {
        "0":".com"
        // and so on...
     },
]
```

In this case, when I press the key, the ".com" value is entered correctly, but it is no longer possible to delete the input with the backspace key.

**Comment by furcan** [comment]
Hi @skullab 

FYI => https://github.com/furcan/KioskBoard/pull/32

Thanks.

**Comment by furcan** [comment]
Hi @skullab ,

KioskBoard v2.0.0 has been released. This issue has been fixed with this release. Also, this is a major release. Please take a look at the [CHANGELOG ](https://github.com/furcan/KioskBoard/blob/main/CHANGELOG.md) before updating your current projects.

Thanks,
Furkan.
