### ISSUE TITLE
Issue with performance on older androids

### ISSUE THREAD

**Issue by RobertDickey** [furcan/KioskBoard#36]
Love the keyboard - but I am noticing that on older devices using ChromeOS or Android and Chrome browser are having performance issues when clicking.  It seems to ignore touches for some time. Would this an animation or latency issue?

**Comment by furcan** [comment]
Hi @RobertDickey ,

I think it might be related to CSS animations as well. You can close it as below.
```js
KioskBoard.init({
    cssAnimations: false,
});
```

Also, you can consider removing the CSS codes as well. There are also other transitions on the CSS file that are related to keypress events.

I will consider extending the `cssAnimations` option to remove all the transitions and animations in the next versions.

Thank you,
Furkan.
