### ISSUE TITLE
Input writing backwards and disappearing after clicking out of input

### ISSUE THREAD

**Issue by robergwillian** [furcan/KioskBoard#38]
Hello again. 

I'm still trying to get your keyboard to work with this project that I have, the issue I'm having now is this: I got the keyboard to showup correctly, however, when I use it to type text into a text field the caracter are writing backwards and when I click out of it the field gets emptied, I've linked a video here on the bottom to show the issue happening. Any idea what could be causing this? BTW this are Material Ui field components.

I appreciate your help!

[Video Here](https://www.youtube.com/watch?v=5slHlKGHuA4)

**Comment by furcan** [comment]
Hi @robergwillian 

I have to see the code to create a solution. The only thing that I can do is suggesting to close real keyboard usages with the options below.

 ```js
allowRealKeyboard: false,
allowMobileKeyboard: false,
```

Thanks,
Furkan.
