### ISSUE TITLE
The Browser has blocked this request by CORS policy.

### ISSUE THREAD

**Issue by surexxx** [furcan/KioskBoard#4]
Lib updated from 1.2.1 to 1.3.0. No code changes at my side.
The Kioskboard doesn't load because of the error 'The Browser has blocked this request by CORS policy.'

Checked the source and I think there is a code bug:
![image](https://user-images.githubusercontent.com/18722513/90654740-fede7e80-e240-11ea-9747-592ea359e795.png)
The 'protocol' variable will never have the value given in the array 'protocolSchemas', because of the ':' postfix (http:).

Chrome version: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by surexxx** [comment]
Here is the w3schools definition of window.location.protocol property: https://www.w3schools.com/jsref/prop_loc_protocol.asp
It always contains ':'
![image](https://user-images.githubusercontent.com/18722513/90655724-313cab80-e242-11ea-9993-5d3372143d88.png)

**Comment by Chousse** [comment]
you should add 'file:' to protocolsshemas array if you want to use kioskboard in electronjs
