### ISSUE TITLE
Can I keep the keyboard positioned in a fixed area?

### ISSUE THREAD

**Issue by SDAdham** [furcan/KioskBoard#40]
Hi, I tried to look around but no lock, any chance I can keep the keyboard always shown and visible and fixed in a certain area on the page?

**Comment by furcan** [comment]
Hi @SDAdham ,

I've designed this library to be open with the focus events because; it would be multiple input elements with different keyboard configurations at the same time on a single page. So on, there is no proper workaround to always keeping the keyboard on the page.

Many thanks,
Furkan.
