### ISSUE TITLE
Possibility to hide mobile keyboard but allow physical keyboard

### ISSUE THREAD

**Issue by rorymeijer** [furcan/KioskBoard#42]
Hi Furcan,

Great script you created!
Could you make a possibility to hide mobile keyboard but allow physical keyboard?

I want to use the physical on my computer but don't want a double keyboard on mobile :)

Many Thanks!

Rory Meijer

**Comment by furcan** [comment]
Hi @rorymeijer ,

Thank you for your comments.

Actually, there is no such option to solve this request but maybe the workaround below might be helpful.

```js
KioskBoard.run('.element', {
  // your options...
  allowRealKeyboard: window.innerWidth > 767, // the breakpoint that you want to use Kioskboard with the real keyboard.
  allowMobileKeyboard: window.innerWidth > 767, // the breakpoint that you want to use Kioskboard with the real keyboard.
});
```

I hope this will be helpful.

Many thanks,
Furkan.
