### ISSUE TITLE
show the cursor in text fields

### ISSUE THREAD

**Issue by DamianoP** [furcan/KioskBoard#43]
An option that allows you to show the classic blinking cursor inside the text fields would be useful

**Comment by furcan** [comment]
Hi @DamianoP,

You can use these two options as `true` to use the input elements as default. 

```js
KioskBoard.run('.element', {
  // your options...
  allowRealKeyboard: true, 
  allowMobileKeyboard: true, 
});
```

Otherwise, there is no such option to show that kind of indicator in the input elements.

Thanks, 
Furkan.
