### ISSUE TITLE
Add dot to numpad keyboard

### ISSUE THREAD

**Issue by SDAdham** [furcan/KioskBoard#45]
Hi, how can I add dot to numpad keyboard?

**Comment by furcan** [comment]
Hi @SDAdham,

 ```js
 /*
  * Optional: An Array of Numbers can be set to override the built-in numpad keys. (From 0 to 9, in any order.)
  * e.g. [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
  */
  keysNumpadArrayOfNumbers: null,
```

Thanks.

**Comment by simonferronforget** [comment]
`keysNumpadArrayOfNumbers` only supports an array of 10 numbers that must be from 0 to 9, in any order.
So, I don't understand how you add "." (dot) to numpad keyboard.

**Comment by furcan** [comment]
Hi @simonferronforget ,

As I have mentioned in this comment it is not possible,

Options: 
1- You can replace any number from this list with a dot. (JavaScript)
2- You can replace any number from this list with a dot and ignore the type check. (TypeScript)

---

> Hi @SDAdham,
> 
> ```js
> /*
>  * Optional: An Array of Numbers can be set to override the built-in numpad keys. (From 0 to 9, in any order.)
>  * e.g. [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
>  */
>  keysNumpadArrayOfNumbers: null,
> ```
> 
> Thanks.

**Comment by osquiabro** [comment]
is possible if a field is a text and add dot to array

<img width="569" alt="image" src="https://github.com/furcan/KioskBoard/assets/58223943/f84d4ac1-468d-4636-b3e7-bc7d02d400e4">
