### ISSUE TITLE
[BUG] - Autoscroll is not working in UWP WebView

### ISSUE THREAD

**Issue by husgab** [furcan/KioskBoard#49]

**Comment by furcan** [comment]
![DAB3C2B2-5E86-4AAE-92A3-C1727F3A07AA](https://user-images.githubusercontent.com/49978011/159371954-dd3cc750-f44f-4203-a03e-48f994f85178.jpeg)

https://github.com/furcan/KioskBoard#browser-compatibility

**Comment by husgab** [comment]
The UWP WebView has Edge browser engine so it should work but it's not working.

**Comment by furcan** [comment]
https://github.com/furcan/KioskBoard/pull/51
