### ISSUE TITLE
[FEAT] - Always show keyboard/numpad 

### ISSUE THREAD

**Issue by newts** [furcan/KioskBoard#54]
This is great but I need to used it in a modal where I always it displayed.  I need to override the typical auto popup.  Is there an easy way to do that?

Ideally I could have an allwaysOn = true or similar

Anything CSS is fine

I also cannot get it to show itself with a click() method.  is there another way?

Thanks!

UPDATE: I see this was already requested but not possible?  I am trying to use it on a 800x480 screen for a device and it is just not possible as it is now.  I can scale it but I need to have it open in javascript or stay always open on my modal.  This is by far the best keyboard I have found and I would really like to get it to work for my application.

**Comment by furcan** [comment]
Hi @newts 

This library is created for being used with multiple input elements at the same time on the same page. So, it is not possible with the current implementation to keep the keyboard always open via an init option.

Maybe you can use the `focus` method on the reference input element if you want to keep the keyboard always open.

```js
theInput.focus();
```

Thanks.

**Comment by dickyermawan** [comment]
> Hi @newts
> 
> This library is created for being used with multiple input elements at the same time on the same page. So, it is not possible with the current implementation to keep the keyboard always open via an init option.
> 
> Maybe you can use the `focus` method on the reference input element if you want to keep the keyboard always open.
> 
> ```js
> theInput.focus();
> ```
> 
> Thanks.

not working for that. i use $('#antrean-no_daftar').focus() but numpad still not show

**Comment by furcan** [comment]
Hi @dickyermawan 

```js
document.querySelector('#antrean-no_daftar').dispatchEvent(new Event('focus'));
```

Can be helpful.

Thanks.

**Comment by dickyermawan** [comment]
> Hi @dickyermawan
> 
> ```js
> document.querySelector('#antrean-no_daftar').dispatchEvent(new Event('focus'));
> ```
> 
> Can be helpful.
> 
> Thanks.

Thanks... it's work.

**Comment by dickyermawan** [comment]
> Hi @dickyermawan
> 
> ```js
> document.querySelector('#antrean-no_daftar').dispatchEvent(new Event('focus'));
> ```
> 
> Can be helpful.
> 
> Thanks.

Hi,, it's work in console. but not work in code.. numpad show and immediately closes in 1sec.. 
any sugesstion ?

#aku is a button 

`$('#aku').on('click', function (e) {
        document.querySelector('#antrean-no_daftar').dispatchEvent(new Event('focus'));
    })`
