### ISSUE TITLE
[FEAT] - Vue 3 / Nuxt JS Integration

### ISSUE THREAD

**Issue by caturandi-labs** [furcan/KioskBoard#59]
Hi Mate, is it possible to integrate kioskboard with nuxt/vue js 3 ?

**Comment by furcan** [comment]
Hi,
It is 99% of not possible. You can try it to be 100% of sure.
Thanks.

**Comment by Soneliem** [comment]
Not sure if anyone else has tried but when I used it with Vue 3 the input would update visually but `v-model` does not update. Additionally `allowRealKeyboard` does not work.
