### ISSUE TITLE
[BUG] - Autoscroll not happening

### ISSUE THREAD

**Issue by revaij83** [furcan/KioskBoard#61]
### Describe the bug
Under special circumstances the keyboard covers the input and the window is not scrolled to make the input visible even though autoscroll is turned on.

E.g.: 
window size: 1024x768
keyboardsize: 1024x540

theInput.getBoundingClientRect()
DOMRect {x: 239, y: 238, width: 546, height: 54, top: 238, …}
bottom: 292
height: 54
left: 239
right: 785
top: 238
width: 546
x: 239
y: 238

### Screenshots
![image](https://user-images.githubusercontent.com/105718665/174062722-299f22b4-fb4e-4b69-a230-f5e1b052eeb9.png)
![image](https://user-images.githubusercontent.com/105718665/174062751-e17acae5-db77-40f8-b5bb-cea36a22c241.png)

**Comment by furcan** [comment]
https://github.com/furcan/KioskBoard/releases/tag/v2.3.0
