### ISSUE TITLE
AllowMobileKeyboard just partially works on iOS

### ISSUE THREAD

**Issue by surexxx** [furcan/KioskBoard#7]
When page has loaded and input has got a focus KioskBoard is showing perfectly without Moblie keyboard. But when user taps into the input or starts to type with KioskBoard, unfortunately iOS shows their keyboard despite AllowMobileKeyboard is false.
![image](https://user-images.githubusercontent.com/18722513/91413234-1c1bda00-e84b-11ea-8d5d-26d2b175d256.png)

I tested with: 
Ipad Pro 12.9" 
iOS 13.6.1 
Chrome browser 85.0.4183.72

On Droid works as expected!

**Comment by furcan** [comment]
Hi @surexxx 

Could you please add the code below to line `276` in the `src/kioskboard.js` on your local/device? 
```js
theInput.blur();
```

<img width="400" alt="Screen Shot 2020-08-27 at 13 08 51" src="https://user-images.githubusercontent.com/49978011/91430588-cefa3100-e867-11ea-8c70-8ce01654b3e4.png">

Then, please feedback about the result. If it works, I will release this fix with the next version. Else, I will re-check for what we can do about that. (I do not have any iPhone or iPad to test it, sorry for this test request.)

Thanks.

**Comment by surexxx** [comment]
Hi @furcan, it's working :) Thanks

**Comment by furcan** [comment]
Hi @surexxx 

That's a good news.

This fix will be included in the next version of KioskBoard. (asap) 

Thank you.
