### ISSUE TITLE
[BUG] - Seeing foreign characters on iOS device displays of the demo page

### ISSUE THREAD

**Issue by jcamachott** [furcan/KioskBoard#73]
### Describe the bug
Seeing extra foreign characters at the end of the custom keyboard on iOS displays

### To Reproduce
1. Visit the demo page on an iPhone or iPad or iPad mini tablet

### Screenshots
![image](https://user-images.githubusercontent.com/1188776/222695926-3ff16318-af89-4666-ba1b-056aa118c685.png)

**Comment by furcan** [comment]
The demo page represents how it works as named "DEMO"

You can please read [README](https://github.com/furcan/KioskBoard/blob/main/README.md) to see how it should be implemented.

<img width="835" alt="Screenshot 2023-03-03 at 15 08 51" src="https://user-images.githubusercontent.com/49978011/222734747-83e91efe-0a0c-4a32-837f-f1ac4388520e.png">

[INIT](https://github.com/furcan/KioskBoard#js--step1-initialize)
